basic_settings:
  site_title: idemeum passwordless demo app
  favicon_image: "/assets/img/favicon/idemeum-favicon.png"

header_settings:
  logo_image: /assets/img/logo/idemeum-logo.png
  mobile_logo_image: /assets/img/logo/idemeum-logo.png
  # Choose a color for your header [blue, dark, light].
  theme: blue
  # If the page has a featured image, it turns transparent if allow_transparent is set to "yes".
  allow_transparent: "no"

home_settings:
  # Choose a layout for your home page:
    # landing – an example landing page made using the Argon design system
    # blog – use your blog posts as the home page
  theme: landing

blog_settings:
  # Choose a format for your blog listings:
    # basic – a simple list of posts
    # narrow – a masonary grid of posts
    # grid – a full-width square grid of posts
  theme: narrow
  # Should we display a narrow grid of other posts at the bottom of each blog post?
  read_more: "no"

# Setup your navigation below – how to use the icons:
  # 1. See all the icons available here https://demos.creative-tim.com/argon-design-system-pro/docs/1.0/foundation/icons.html
  # 2. Get the name of the icon e.g basket, then prefix with ni to make ni-basket.
  # 3. Add a color of the icon - text-primary, text-success, text-info, text-danger, text-warning and text-default all work!
menu_settings:
  menu_items:
  #- title: Docs
    #url: https://docs.idemeum.com
  #- title: 'Pricing'
    #url: https://idemeum.com/pricing
  #- title: 'Resources'
    #submenu_items:
    # - title: Blog
       #url: https://blog.idemeum.com
       #icon: ni ni-books text-warning
     #- title: Live demo
       #url: https://jsdemo.idemeum.com
       #icon: ni ni-tv-2 text-success
  #- title: 'Company'
    #submenu_items:
    #- title: About idemeum
      #url: https://idemeum.com/about
      #icon: ni ni-spaceship text-success
    #- title: Contact us
      #url: https://idemeum.com/contact
      #icon: fa fa-envelope text-warning